org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=18080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=18080 
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.max.workers=1
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.enableDexingArtifactTransform=false
